// React/src/components/footer/footer.jsx
import React from 'react'

const footer = () => {
    return (
        <>
            <footer class="row row-cols-5 py-5 mt-5 border-top bg-dark w-100 mx-auto">
                <div class="col">
                    <a href="/" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
                    </a>
                    <p class="text-white"><a className="navbar-brand text-info heading fs-3" href="#">Moogle</a>© 2021</p>
                </div>

                <div class="col">

                </div>

                <div class="col">
                    <h5 className="text-white">Links</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Blogs</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Account</a></li>
                    </ul>
                </div>

                <div class="col">
                    <h5 className="text-white">Connect Us</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white fs-1"><i class="fab fa-instagram"></i></a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-white fs-1"><i class="fab fa-twitter"></i></a></li>
                    </ul>
                </div>

                <div class="col">
                    <h5 className="text-white">Contact Us</h5>
                    <ul class="nav flex-column">
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">+91-8483928849</a></li>
                        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">contact@moogle.css</a></li>

                    </ul>
                </div>
            </footer>
        </>
    )
}

export default footer

// svelte/src/components/footer/footer.svelte
<footer class="row row-cols-5 py-5 mt-5 border-top bg-dark w-100 mx-auto">
    <div class="col">
        <a href="/" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
        </a>
        <p class="text-white"><a class="navbar-brand text-info heading fs-3" href="/">Moogle</a>© 2021</p>
    </div>

    <div class="col">

    </div>

    <div class="col">
        <h5 class="text-white">Links</h5>
        <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="/" class="nav-link p-0 text-muted">Home</a></li>
            <li class="nav-item mb-2"><a href="/#/blogs" class="nav-link p-0 text-muted">Blogs</a></li>
            <li class="nav-item mb-2"><a href="/#/about" class="nav-link p-0 text-muted">About</a></li>
            <li class="nav-item mb-2"><a href="/#/account" class="nav-link p-0 text-muted">Account</a></li>
        </ul>
    </div>

    <div class="col">
        <h5 class="text-white">Connect Us</h5>
        <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="/" class="nav-link p-0 text-white fs-1"><i class="fab fa-instagram"></i></a></li>
            <li class="nav-item mb-2"><a href="/" class="nav-link p-0 text-white fs-1"><i class="fab fa-twitter"></i></a></li>
        </ul>
    </div>

    <div class="col">
        <h5 class="text-white">Contact Us</h5>
        <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="/" class="nav-link p-0 text-muted">+91-8483928849</a></li>
            <li class="nav-item mb-2"><a href="/" class="nav-link p-0 text-muted">contact@moogle.css</a></li>

        </ul>
    </div>
</footer>
